### ISSUE TITLE
mzml read issue

### ISSUE THREAD

**Issue by stotlanda** [syjgino/SLA#4]
Hello,

I am trying to analyze some data I've aqcuired using the SLA methods, but I am getting the following error when I hit "Read MzML":

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "LApack_V1.3.py", line 264, in <lambda>
  File "Tab3Readmzml1_3.py", line 226, in readMZML
AttributeError: 'NoneType' object has no attribute 'group'

I thought it may have been a conversion issue, as I've had multiple wiff files in the batch, and so I split them before conversion, but am still getting this error. Apologies if I've missed something obvious,

Best

**Comment by FabRiols** [comment]
Hello,
I think your issue comes from the data file names:
##get method number
        method = re.search('- (.)-', list_of_files[sample]).group(1)
Before conversion into mzml files, your wiff files need to be named according to the code above (with right number of hyphen and spaces).
By the way you can find it in the SLA_v4_SOP:
"_a.	When creating a batch/set, the name should follow the format “name - date – method”. For example, “Lipidomics – 20220101 – 1” for a batch using method 1._"
Otherwise it cannot distinguish files from method 01 and 02.

Normally you should have initially two wiff files, one for each method. Then by using MSconvertGui, every sample data is extracted and converted into mzml files. So you get for instance: Lipidomics – 20220101 – 1-SampleName01.mzML and Lipidomics – 20220101 – 2-SampleName01.mzML, etc....

Best,

**Comment by stotlanda** [comment]
Thank you very much for your quick response, that solved the problem. Best, and thank you again for your time and efforts

A
